"""
Simple test script to verify the system works
This can be run without the web interface to test core functionality
"""

import os
import sys
from dotenv import load_dotenv
from pathlib import Path

# Add the backend directory to the path
backend_dir = Path(__file__).parent
sys.path.insert(0, str(backend_dir))

def main():
    print("=== Self-Evaluating Lesson Generator - Simple Test ===\n")
    
    # Load environment variables
    load_dotenv(backend_dir / '.env')
    
    # Check for API key
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key or api_key == "your_openai_api_key_here":
        print("❌ OPENAI_API_KEY not configured!")
        print("Please add your OpenAI API key to app/backend/.env file:")
        print("OPENAI_API_KEY=sk-your-actual-api-key-here")
        return
    
    print("✅ OPENAI_API_KEY found")
    
    try:
        # Import components
        from evaluation_rubric import LessonRubric
        print("✅ Evaluation rubric imported successfully")
        
        # Test rubric
        rubric = LessonRubric()
        print(f"✅ Rubric initialized with {len(rubric.checkpoints)} checkpoints")
        
        # Test agentic system import
        from agentic_system import AgenticLessonSystem
        print("✅ Agentic system imported successfully")
        
        # Initialize system with conservative settings for testing
        print("\n🚀 Initializing agentic system...")
        system = AgenticLessonSystem(
            api_key=api_key,
            max_iterations=2,  # Reduced for testing
            min_pass_rate=80.0  # Reduced for testing
        )
        print("✅ Agentic system initialized")
        
        # Test with a simple topic first
        print("\n🧪 Testing with simple topic: 'Introduction to Python'...")
        try:
            result = system.generate_lesson("Introduction to Python")
            
            print(f"\n✅ Test completed successfully!")
            print(f"   Success: {result['success']}")
            print(f"   Iterations: {result['total_iterations']}")
            print(f"   Pass rate: {result['final_evaluation']['pass_rate']:.1f}%")
            
            # Save result
            import json
            output_file = backend_dir / "simple_test_result.json"
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(result, f, indent=2, default=str)
            print(f"   Results saved to: {output_file}")
            
        except Exception as e:
            print(f"❌ Generation test failed: {e}")
            import traceback
            traceback.print_exc()
            return
        
        # Now test with the required RAG topic
        print("\n🎯 Testing with required topic: 'RAG (Retrieval-Augmented Generation)'...")
        system.reset_session()
        
        try:
            result = system.generate_lesson("RAG (Retrieval-Augmented Generation)")
            
            print(f"\n✅ RAG lesson generation completed!")
            print(f"   Success: {result['success']}")
            print(f"   Iterations: {result['total_iterations']}")
            print(f"   Pass rate: {result['final_evaluation']['pass_rate']:.1f}%")
            
            # Save RAG result
            output_file = backend_dir / "rag_lesson_result.json"
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(result, f, indent=2, default=str)
            print(f"   RAG results saved to: {output_file}")
            
            # Save the lesson as markdown
            lesson_file = backend_dir / "RAG_Introduction_Lesson.md"
            with open(lesson_file, 'w', encoding='utf-8') as f:
                f.write(f"# Lesson: {result['topic']}\n\n")
                f.write(f"## Quality Metrics\n")
                f.write(f"- Pass Rate: {result['final_evaluation']['pass_rate']:.1f}%\n")
                f.write(f"- Checkpoints Passed: {result['final_evaluation']['rubric_summary']['passed_count']}/{result['final_evaluation']['rubric_summary']['total_checkpoints']}\n")
                f.write(f"- Iterations Required: {result['total_iterations']}\n")
                f.write(f"- Success: {result['success']}\n\n")
                f.write(f"## Lesson Content\n\n")
                f.write(result['final_lesson'])
                f.write(f"\n\n---\n")
                f.write(f"Generated by Self-Evaluating Lesson Generator\n")
            print(f"   RAG lesson saved as markdown: {lesson_file}")
            
        except Exception as e:
            print(f"❌ RAG generation failed: {e}")
            import traceback
            traceback.print_exc()
            return
        
        print("\n" + "="*60)
        print("🎉 ALL TESTS PASSED!")
        print("="*60)
        print("\nThe system is working correctly and ready for use.")
        print("You can now:")
        print("1. Start the backend server: uvicorn server:app --reload")
        print("2. Start the frontend: cd app/frontend && npm start")
        print("3. Access the web interface at http://localhost:3000")
        
    except ImportError as e:
        print(f"❌ Import error: {e}")
        print("Make sure you have installed all dependencies:")
        print("cd app/backend && pip install -r requirements.txt")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()